version: '3'
services:
  back:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: dl
     POSTGRES_USER: dl
   ports:
    - "5432:5432"
  front:
    restart: always
    build: ../front/
    ports:
      - 8000:8000
    depends_on:
      - back
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FB411452A47D9D99
      MINIO_SECRET_KEY: IbD0LlxwJkZdKOlFufpvw0rtqsTT4i1D
    volumes:
      - ../minio-data:/data
    command: server /data