version: '3'
services:
  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: dl
     POSTGRES_USER: dl
   ports:
    - "5432:5432"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FB411452A47D9D99
      MINIO_SECRET_KEY: IbD0LlxwJkZdKOlFufpvw0rtqsTT4i1D
    volumes:
      - ../minio-data:/data
    command: server /data