version: '3'
services:
  back:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
  auth:
    restart: always
    build: ../auth
    depends_on:
      - redis
    ports:
      - "9325:9325"
  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: dl
     POSTGRES_USER: dl
   ports:
    - "5432:5432"
  front:
    restart: always
    build: ../front/
    ports:
      - 8000:8000
    depends_on:
      - back
  courier_front:
    restart: always
    build: ../courier_front/
    ports:
      - 8008:8008
    depends_on:
      - back
      - front
  redis:
    image: redis
    restart: always
