# Generated by Django 2.1.7 on 2019-03-17 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='goods/')),
                ('description', models.CharField(max_length=1024)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsQuatityOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.PositiveIntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Horecama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('photo', models.ImageField(upload_to='horecama/')),
                ('type', models.CharField(choices=[('H', 'Hotel'), ('R', 'Restaurant'), ('C', 'Cafe'), ('M', 'Markets')], max_length=1)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_name', models.CharField(max_length=128)),
                ('user_phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=512)),
                ('delivered', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('goods', models.ManyToManyField(related_name='orders', through='core.GoodsQuatityOrder', to='core.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='goodsquatityorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AddField(
            model_name='goods',
            name='horecama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.Horecama'),
        ),
    ]
