# Generated by Django 2.1.7 on 2019-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horecama',
            name='photo',
            field=models.ImageField(blank=True, upload_to='horecama/'),
        ),
    ]
