# Generated by Django 2.1.7 on 2019-03-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190317_1755'),
        ('core', '0002_auto_20190317_1937'),
    ]

    operations = [
    ]
